### PR TITLE
Jack Jackrum Compatibility issue#12

### PR DESCRIPTION
**Pull request by LouisOuellet**
So I am currently working on updating the Writr template to Jack Jackrum. While working on plugin compatibility, I notice BlogLinks having issues with some undefined variables.

```bash
[28-Dec-2023 05:07:53 UTC] PHP Warning:  Undefined array key "type" in [WEBROOT]/lib/plugins/bloglinks/action.php on line 114
[28-Dec-2023 05:07:53 UTC] PHP Warning:  Undefined variable $next in [WEBROOT]/lib/plugins/bloglinks/action.php on line 129
[28-Dec-2023 05:07:53 UTC] PHP Warning:  Undefined array key "type" in [WEBROOT]/lib/plugins/bloglinks/action.php on line 114
[28-Dec-2023 05:07:53 UTC] PHP Warning:  Undefined variable $next in [WEBROOT]/lib/plugins/bloglinks/action.php on line 129
```

I am currently running my dev environment on Apache and PHP8.1. On MAMP.

--

Here is a proposed fixed for the issue #12.

### CODE REVIEW

**Comment by Klap-in** [comment]
Thanks for contributing!
Could you please remove the date and time from future commit messages? These are already stored as metadata of the commit. Instead describe what you did in the specific commit, such that if someone has to search back in the history (see for example here: [history](https://github.com/LouisOuellet/plugin-bloglinks/commits/dev/)) the reader knows which commits might be interesting.

**Comment by Klap-in** [comment]
I have removed the VERSION file, as these are not used (anymore?). Instead I have updated the plugin.info.txt which is used by the Extension manager.

**Comment by LouisOuellet** [comment]
> Thanks for contributing! Could you please remove the date and time from future commit messages? These are already stored as metadata of the commit. Instead describe what you did in the specific commit, such that if someone has to search back in the history (see for example here: [history](https://github.com/LouisOuellet/plugin-bloglinks/commits/dev/)) the reader knows which commits might be interesting.

Well thanks for the tip, even though I have a lot of stuff on github, I am still used to my old ways. Most projects I worked on are either private(proprietary) or I am the only contributor. So I haven't have much experience with this tool yet. Learning as I go. I had written a macro in my .bash_aliases to execute all the git commands. Might just go and modify it to remove the Version and Date with a switch or something.

**Comment by Klap-in** [comment]
Thanks for considering :-)
Probably you know already quite a bit, but maybe this page has still some interesting notes about how we use git for collaborating on DokuWiki and its plugins/templates: https://www.dokuwiki.org/devel:git

**Comment by LouisOuellet** [comment]
> Thanks for considering :-) Probably you know already quite a bit, but maybe this page has still some interesting notes about how we use git for collaborating on DokuWiki and its plugins/templates: https://www.dokuwiki.org/devel:git

How about this : [history](https://github.com/LouisOuellet/dokuwiki_template_writr2/commits/dev/)? Is this better? Otherwise do you have other tips to give me?

**Comment by Klap-in** [comment]
This makes your history understandable, nice!! A final addition is that you can add (often just in some words) why you need this change. If you have in the future a conflicting change, you can search for the commit message where you or someone else added what you thought it would do _and_ why it was useful at that time, so that you can check whether it is still relevant for your new situation.

Where a change was introduced can be find back with help of the “blame” function. e.g. [blame on main.php](https://github.com/LouisOuellet/dokuwiki_template_writr2/blame/master/main.php).

**Comment by LouisOuellet** [comment]
> This makes your history understandable, nice!! A final addition is that you can add (often just in some words) why you need this change. If you have in the future a conflicting change, you can search for the commit message where you or someone else added what you thought it would do _and_ why it was useful at that time, so that you can check whether it is still relevant for your new situation.
> 
> Where a change was introduced can be find back with help of the “blame” function. e.g. [blame on main.php](https://github.com/LouisOuellet/dokuwiki_template_writr2/blame/master/main.php).

Good to know! thanks again for the tips. Looking forward to contribute to more Dokuwiki related repos.

**Pull request merged**
